repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        args: ["--check", "--diff", "--color", "."]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies:
          - pyproject-flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--check-only", "--diff", "--color", "."]
        additional_dependencies: [colorama]
