name: Check workflow running linter, unit and functional tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, main]
    paths-ignore:
      - "**.md"
      - "**.rst"

jobs:
  lint-unit:
    uses: canonical/bootstack-actions/.github/workflows/lint-unit.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]
    with:
      python-version: ${{ matrix.python-version }}
      tox-version: "<4"

  func:
    uses: canonical/bootstack-actions/.github/workflows/func.yaml@v3
    needs: lint-unit
    strategy:
      fail-fast: false
    with:
      command: "TEST_JUJU3=1 make functional"  # using TEST_JUJU3 due https://github.com/openstack-charmers/zaza/commit/af7eea953dd5d74d3d074fe67b5765dca3911ca6
      runs-on: "['self-hosted', 'xlarge', 'jammy', 'x64']"
      juju-channel: "3.4/stable"
      nested-containers: false
      provider: "lxd"
      python-version: "3.10"
      timeout-minutes: 120
      tox-version: "<4"
